In [1]:
import pandas as pd

# 2 Main Datatypes

In [5]:
series = pd.Series(["BMW", "Mercedes", "Audi"])

In [6]:
series

0         BMW
1    Mercedes
2        Audi
dtype: str

# Series = 1 Dimensional

In [9]:
colours = pd.Series(["Black", "Magenta", "White"])
colours

0      Black
1    Magenta
2      White
dtype: str

# DataFrame = 2 Dimensional

In [26]:
car_data = pd.DataFrame({"Cars": series, "Colours": colours})
car_data
# car_data.iloc[2,1]

       Cars  Colours
0       BMW    Black
1  Mercedes  Magenta
2      Audi    White

# IMPORTING DATA

In [29]:
car_sales = pd.read_csv("cars_dataset.csv")
car_sales

                    Make  Colour  Odometer (km)  Doors  Price (INR)
0      Mercedes-Benz GLC   Black           6556      4      2923000
1      Volkswagen Virtus   Black         177392      4       605000
2           Ford Mustang   White           7811      3       717000
3            Honda Civic   Green          52124      4      1368000
4          Tesla Model 3   Brown         154472      4      1573000
..                   ...     ...            ...    ...          ...
495          Toyota RAV4   Black          77445      4       794000
496           Kia Carens  Silver          91312      4      1036000
497            Kia Sonet   Brown          91304      4       978000
498        Porsche Macan     Red          17609      4      4913000
499  Maruti Suzuki Swift   Black         177508      4       485000

[500 rows x 5 columns]

# Importing Data

In [32]:
car_sales.to_csv("exported-car-sales.csv", index = False)

Well, WE used index = False so pandas wouldn't write the DataFrame's index NO. as an additional column in  exported CSV file. as we only want our actual data columns, not the extra index column.

In [35]:
exported_car_sales = pd.read_csv("exported-car-sales.csv")
exported_car_sales

                    Make  Colour  Odometer (km)  Doors  Price (INR)
0      Mercedes-Benz GLC   Black           6556      4      2923000
1      Volkswagen Virtus   Black         177392      4       605000
2           Ford Mustang   White           7811      3       717000
3            Honda Civic   Green          52124      4      1368000
4          Tesla Model 3   Brown         154472      4      1573000
..                   ...     ...            ...    ...          ...
495          Toyota RAV4   Black          77445      4       794000
496           Kia Carens  Silver          91312      4      1036000
497            Kia Sonet   Brown          91304      4       978000
498        Porsche Macan     Red          17609      4      4913000
499  Maruti Suzuki Swift   Black         177508      4       485000

[500 rows x 5 columns]

With that, we've learned about the main data structures: DataFrames and Series, + how to import and export data, && cleared up all the doubts we had along the way with the help of our dearest tutor AI, haha.