In [2]:
import numpy as np


# DataTypes and Attributes

 Numpy's main datatype is ndarray (N-Dimensional array!)

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.0,3.3], [4, 5, 6.5]])

a3 = np.array([[[1,2,3],
                [4, 5, 6],
                [7, 8, 9]], 
               [[10, 11, 12],  
               [13, 14, 15], 
               [16, 17, 18]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1

array([1, 2, 3])

In [12]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [13]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [14]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [15]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [16]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [17]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Create a DataFrame from a Numpy array.

In [19]:
import pandas as pd

In [20]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [21]:
df2 = pd.DataFrame(a2)

In [22]:
df2

     0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [23]:
a1

array([1, 2, 3])

In [24]:
df1 = pd.DataFrame(a1)

In [25]:
df1

   0
0  1
1  2
2  3