# Manipulating Data - Part I, II, and III

In [3]:
import pandas as pd

In [4]:
car_sales = pd.read_csv("exported-car-sales.csv")

In [81]:
car_sales.head(10)

                  Make       Colour  Odometer (km)  Doors  Price (INR)
0    Mercedes-Benz GLC        Black           6556      4      2923000
1    Volkswagen Virtus        Black         177392      4       605000
2         Ford Mustang        White           7811      3       717000
3          Honda Civic        Green          52124      4      1368000
4        Tesla Model 3        Brown         154472      4      1573000
5         BMW 3 Series  Pearl White          89194      4      3469000
6  Maruti Suzuki Swift        Black          24312      4      1065000
7         BMW 5 Series         Blue         211583      2      2900000
8            MG Hector        Black         144714      4      2258000
9           Kia Seltos       Yellow          50407      4       416000

In [37]:
car_sales_original = car_sales.copy()

I created an copy just in case so we can return back to our original data

In [38]:
car_sales_original

                    Make  Colour  Odometer (km)  Doors  Price (INR)
0      Mercedes-Benz GLC   Black           6556      4      2923000
1      Volkswagen Virtus   Black         177392      4       605000
2           Ford Mustang   White           7811      3       717000
3            Honda Civic   Green          52124      4      1368000
4          Tesla Model 3   Brown         154472      4      1573000
..                   ...     ...            ...    ...          ...
495          Toyota RAV4   Black          77445      4       794000
496           Kia Carens  Silver          91312      4      1036000
497            Kia Sonet   Brown          91304      4       978000
498        Porsche Macan     Red          17609      4      4913000
499  Maruti Suzuki Swift   Black         177508      4       485000

[500 rows x 5 columns]

In [39]:
car_sales["Make"].str.lower().head(10)

0      mercedes-benz glc
1      volkswagen virtus
2           ford mustang
3            honda civic
4          tesla model 3
5           bmw 3 series
6    maruti suzuki swift
7           bmw 5 series
8              mg hector
9             kia seltos
Name: Make, dtype: str

In [10]:
# car_sales["Make"]

0        Mercedes-Benz GLC
1        Volkswagen Virtus
2             Ford Mustang
3              Honda Civic
4            Tesla Model 3
              ...
495            Toyota RAV4
496             Kia Carens
497              Kia Sonet
498          Porsche Macan
499    Maruti Suzuki Swift
Name: Make, Length: 500, dtype: str

.str.lower() → converts all alphabetic characters in each string to lowercase, but. but. but. it doesn't permanently change the original column unless we assign the result back to it.

In [42]:
car_sales["Make"] = car_sales["Make"].str.lower()

In [43]:
car_sales

                    Make  Colour  Odometer (km)  Doors  Price (INR)
0      mercedes-benz glc   Black           6556      4      2923000
1      volkswagen virtus   Black         177392      4       605000
2           ford mustang   White           7811      3       717000
3            honda civic   Green          52124      4      1368000
4          tesla model 3   Brown         154472      4      1573000
..                   ...     ...            ...    ...          ...
495          toyota rav4   Black          77445      4       794000
496           kia carens  Silver          91312      4      1036000
497            kia sonet   Brown          91304      4       978000
498        porsche macan     Red          17609      4      4913000
499  maruti suzuki swift   Black         177508      4       485000

[500 rows x 5 columns]

Successfully changed!!!!!!!!!!!!

In [44]:
car_sales_original

                    Make  Colour  Odometer (km)  Doors  Price (INR)
0      Mercedes-Benz GLC   Black           6556      4      2923000
1      Volkswagen Virtus   Black         177392      4       605000
2           Ford Mustang   White           7811      3       717000
3            Honda Civic   Green          52124      4      1368000
4          Tesla Model 3   Brown         154472      4      1573000
..                   ...     ...            ...    ...          ...
495          Toyota RAV4   Black          77445      4       794000
496           Kia Carens  Silver          91312      4      1036000
497            Kia Sonet   Brown          91304      4       978000
498        Porsche Macan     Red          17609      4      4913000
499  Maruti Suzuki Swift   Black         177508      4       485000

[500 rows x 5 columns]

In [46]:
# car_sales["Odometer (km)"].str.lower()

AttributeError: Can only use .str accessor with string values, not integer

Gotcha LOLLLL!!!!!!!!

In [65]:
car_sales_missing = pd.read_csv("car-sales-missing-data.csv")

In [66]:
car_sales_missing

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

Let's fill in the missing values in the "Odometer" column.

In [67]:
car_sales_missing["Odometer"].apply(type).value_counts()

Odometer
<class 'float'>    10
Name: count, dtype: int64

In [68]:
car_sales_missing["Odometer"].mean()

np.float64(92302.66666666667)

In [84]:
# car_sales_missing["Odometer"]= car_sales_missing["Odometer"].fillna(car_sales_missing["Odometer"].mean())

# OR

car_sales_missing["Odometer"].fillna(car_sales_missing["Odometer"].mean(), inplace=True)

/var/folders/y6/zs_ytw191kz20026r2gs_bw00000gn/T/ipykernel_9752/3900543621.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  car_sales_missing["Odometer"].fillna(car_sales_missing["Odometer"].mean(), inplace=True)

0    150043.000000
1     87899.000000
2     92302.666667
3     11179.000000
4    213095.000000
5     92302.666667
Name: Odometer, dtype: float64

In [70]:
car_sales_missing

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500
6   Honda    NaN   92302.666667    4.0   $7,500
7   Honda   Blue   92302.666667    4.0      NaN
8  Toyota  White   60000.000000    NaN      NaN
9     NaN  White   31600.000000    4.0   $9,700

In [82]:
car_sales_missing.dropna(inplace=True)

In [83]:
car_sales_missing

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500

Let's reset it back to where it was (with originals)

In [86]:
car_sales_missing = pd.read_csv("car-sales-missing-data.csv")

In [87]:
car_sales_missing

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

In [89]:
car_sales_missing_dropped = car_sales_missing.dropna()

Well. Well. Well. dropna() creates and returns a new DataFrame with rows containing NaN removed completely, which means leaving the original unchanged.

+In our case, we saved the cleaned data in car_sales_missing_dropped, while keeping our original DataFrame unchanged.

In [91]:
car_sales_missing_dropped.to_csv("car-sales-missing-drop.csv")

# PART II

let's see how do we create data from existing data

### 1. Column from series.

In [10]:
seats_column = pd.Series([5]*500)
seats_column

0      5
1      5
2      5
3      5
4      5
      ..
495    5
496    5
497    5
498    5
499    5
Length: 500, dtype: int64

In [93]:
car_sales.head(10)

                  Make       Colour  Odometer (km)  Doors  Price (INR)
0    Mercedes-Benz GLC        Black           6556      4      2923000
1    Volkswagen Virtus        Black         177392      4       605000
2         Ford Mustang        White           7811      3       717000
3          Honda Civic        Green          52124      4      1368000
4        Tesla Model 3        Brown         154472      4      1573000
5         BMW 3 Series  Pearl White          89194      4      3469000
6  Maruti Suzuki Swift        Black          24312      4      1065000
7         BMW 5 Series         Blue         211583      2      2900000
8            MG Hector        Black         144714      4      2258000
9           Kia Seltos       Yellow          50407      4       416000

In [11]:
car_sales["Seats"] = seats_column

In [102]:
car_sales

                    Make  Colour  Odometer (km)  Doors  Price (INR)  Seats
0      Mercedes-Benz GLC   Black           6556      4      2923000      5
1      Volkswagen Virtus   Black         177392      4       605000      5
2           Ford Mustang   White           7811      3       717000      5
3            Honda Civic   Green          52124      4      1368000      5
4          Tesla Model 3   Brown         154472      4      1573000      5
..                   ...     ...            ...    ...          ...    ...
495          Toyota RAV4   Black          77445      4       794000      5
496           Kia Carens  Silver          91312      4      1036000      5
497            Kia Sonet   Brown          91304      4       978000      5
498        Porsche Macan     Red          17609      4      4913000      5
499  Maruti Suzuki Swift   Black         177508      4       485000      5

[500 rows x 6 columns]

In [104]:
Tier_column = pd.Series([4]*6)

In [105]:
Tier_column

0    4
1    4
2    4
3    4
4    4
5    4
dtype: int64

In [106]:
car_sales["Tier"] = Tier_column

In [109]:
car_sales.head(10)

,Make,Colour,Odometer (km),Doors,Price (INR),Seats,Tier
0,Mercedes-Benz GLC,Black,6556,4,2923000,5,4.0
1,Volkswagen Virtus,Black,177392,4,605000,5,4.0
2,Ford Mustang,White,7811,3,717000,5,4.0
3,Honda Civic,Green,52124,4,1368000,5,4.0
4,Tesla Model 3,Brown,154472,4,1573000,5,4.0
5,BMW 3 Series,Pearl White,89194,4,3469000,5,4.0
6,Maruti Suzuki Swift,Black,24312,4,1065000,5,NaN
7,BMW 5 Series,Blue,211583,2,2900000,5,NaN
8,MG Hector,Black,144714,4,2258000,5,NaN
9,Kia Seltos,Yellow,50407,4,416000,5,NaN

Let’s use the fillna() method to replace the missing (NaN) values in Tier section.

In [114]:
car_sales["Tier"] = car_sales["Tier"].fillna(4)

In [115]:
car_sales

,Make,Colour,Odometer (km),Doors,Price (INR),Seats,Tier
0,Mercedes-Benz GLC,Black,6556,4,2923000,5,4.0
1,Volkswagen Virtus,Black,177392,4,605000,5,4.0
2,Ford Mustang,White,7811,3,717000,5,4.0
3,Honda Civic,Green,52124,4,1368000,5,4.0
4,Tesla Model 3,Brown,154472,4,1573000,5,4.0
...,...,...,...,...,...,...,...
495,Toyota RAV4,Black,77445,4,794000,5,4.0
496,Kia Carens,Silver,91312,4,1036000,5,4.0
497,Kia Sonet,Brown,91304,4,978000,5,4.0
498,Porsche Macan,Red,17609,4,4913000,5,4.0
499,Maruti Suzuki Swift,Black,177508,4,485000,5,4.0

### 2. Column from List.

In [119]:
Fuel_economy = [7.5, 9.2, 5.0, 9.6, 8.7, 4.7, 8.8]
car_sales["Fuel per 100KM"] = Fuel_economy

ValueError: Length of values (7) does not match length of index (500)

HAHA - The ValueError occurs because our Python list contains only 7 values,

while car_sales has 500 rows. It's like this when creating a column using a list, its length must match the number of rows in the DataFrame.

In [6]:
Fuel_economy = [ 8.8]*500
car_sales["Fuel per 100KM"] = Fuel_economy

In [121]:
car_sales

,Make,Colour,Odometer (km),Doors,Price (INR),Seats,Tier,Fuel per 100KM
0,Mercedes-Benz GLC,Black,6556,4,2923000,5,4.0,8.8
1,Volkswagen Virtus,Black,177392,4,605000,5,4.0,8.8
2,Ford Mustang,White,7811,3,717000,5,4.0,8.8
3,Honda Civic,Green,52124,4,1368000,5,4.0,8.8
4,Tesla Model 3,Brown,154472,4,1573000,5,4.0,8.8
...,...,...,...,...,...,...,...,...
495,Toyota RAV4,Black,77445,4,794000,5,4.0,8.8
496,Kia Carens,Silver,91312,4,1036000,5,4.0,8.8
497,Kia Sonet,Brown,91304,4,978000,5,4.0,8.8
498,Porsche Macan,Red,17609,4,4913000,5,4.0,8.8
499,Maruti Suzuki Swift,Black,177508,4,485000,5,4.0,8.8

In [123]:
car_sales["Total fuel used"] = car_sales["Odometer (km)"]/100 * car_sales["Fuel per 100KM"]

In [124]:
car_sales

,Make,Colour,Odometer (km),Doors,Price (INR),Seats,Tier,Fuel per 100KM,Total fuel used
0,Mercedes-Benz GLC,Black,6556,4,2923000,5,4.0,8.8,576.928
1,Volkswagen Virtus,Black,177392,4,605000,5,4.0,8.8,15610.496
2,Ford Mustang,White,7811,3,717000,5,4.0,8.8,687.368
3,Honda Civic,Green,52124,4,1368000,5,4.0,8.8,4586.912
4,Tesla Model 3,Brown,154472,4,1573000,5,4.0,8.8,13593.536
...,...,...,...,...,...,...,...,...,...
495,Toyota RAV4,Black,77445,4,794000,5,4.0,8.8,6815.160
496,Kia Carens,Silver,91312,4,1036000,5,4.0,8.8,8035.456
497,Kia Sonet,Brown,91304,4,978000,5,4.0,8.8,8034.752
498,Porsche Macan,Red,17609,4,4913000,5,4.0,8.8,1549.592
499,Maruti Suzuki Swift,Black,177508,4,485000,5,4.0,8.8,15620.704

### 3. Create a column from a single value

In [125]:
car_sales["Roof"] = 1

In [126]:
car_sales

,Make,Colour,Odometer (km),Doors,Price (INR),Seats,Tier,Fuel per 100KM,Total fuel used,Roof
0,Mercedes-Benz GLC,Black,6556,4,2923000,5,4.0,8.8,576.928,1
1,Volkswagen Virtus,Black,177392,4,605000,5,4.0,8.8,15610.496,1
2,Ford Mustang,White,7811,3,717000,5,4.0,8.8,687.368,1
3,Honda Civic,Green,52124,4,1368000,5,4.0,8.8,4586.912,1
4,Tesla Model 3,Brown,154472,4,1573000,5,4.0,8.8,13593.536,1
...,...,...,...,...,...,...,...,...,...,...
495,Toyota RAV4,Black,77445,4,794000,5,4.0,8.8,6815.160,1
496,Kia Carens,Silver,91312,4,1036000,5,4.0,8.8,8035.456,1
497,Kia Sonet,Brown,91304,4,978000,5,4.0,8.8,8034.752,1
498,Porsche Macan,Red,17609,4,4913000,5,4.0,8.8,1549.592,1
499,Maruti Suzuki Swift,Black,177508,4,485000,5,4.0,8.8,15620.704,1

In [13]:
car_sales["Passed road safety"] = True

In [14]:
car_sales.dtypes

Make                      str
Colour                    str
Odometer (km)           int64
Doors                   int64
Price (INR)             int64
Fuel per 100KM        float64
Total fuel used       float64
Seats                   int64
Passed road safety       bool
dtype: object

In [130]:
car_sales

,Make,Colour,Odometer (km),Doors,Price (INR),Seats,Tier,Fuel per 100KM,Total fuel used,Roof,Passed road safety
0,Mercedes-Benz GLC,Black,6556,4,2923000,5,4.0,8.8,576.928,1,True
1,Volkswagen Virtus,Black,177392,4,605000,5,4.0,8.8,15610.496,1,True
2,Ford Mustang,White,7811,3,717000,5,4.0,8.8,687.368,1,True
3,Honda Civic,Green,52124,4,1368000,5,4.0,8.8,4586.912,1,True
4,Tesla Model 3,Brown,154472,4,1573000,5,4.0,8.8,13593.536,1,True
...,...,...,...,...,...,...,...,...,...,...,...
495,Toyota RAV4,Black,77445,4,794000,5,4.0,8.8,6815.160,1,True
496,Kia Carens,Silver,91312,4,1036000,5,4.0,8.8,8035.456,1,True
497,Kia Sonet,Brown,91304,4,978000,5,4.0,8.8,8034.752,1,True
498,Porsche Macan,Red,17609,4,4913000,5,4.0,8.8,1549.592,1,True
499,Maruti Suzuki Swift,Black,177508,4,485000,5,4.0,8.8,15620.704,1,True

Let’s drop (delete) one of the columns!

In [131]:
car_sales = car_sales.drop("Total fuel used", axis=1)

In [132]:
car_sales

,Make,Colour,Odometer (km),Doors,Price (INR),Seats,Tier,Fuel per 100KM,Roof,Passed road safety
0,Mercedes-Benz GLC,Black,6556,4,2923000,5,4.0,8.8,1,True
1,Volkswagen Virtus,Black,177392,4,605000,5,4.0,8.8,1,True
2,Ford Mustang,White,7811,3,717000,5,4.0,8.8,1,True
3,Honda Civic,Green,52124,4,1368000,5,4.0,8.8,1,True
4,Tesla Model 3,Brown,154472,4,1573000,5,4.0,8.8,1,True
...,...,...,...,...,...,...,...,...,...,...
495,Toyota RAV4,Black,77445,4,794000,5,4.0,8.8,1,True
496,Kia Carens,Silver,91312,4,1036000,5,4.0,8.8,1,True
497,Kia Sonet,Brown,91304,4,978000,5,4.0,8.8,1,True
498,Porsche Macan,Red,17609,4,4913000,5,4.0,8.8,1,True
499,Maruti Suzuki Swift,Black,177508,4,485000,5,4.0,8.8,1,True

In [7]:
car_sales["Total fuel used"] = car_sales["Odometer (km)"]/100 * car_sales["Fuel per 100KM"]

# PART III

In [16]:
car_sales.head(10)

,Make,Colour,Odometer (km),Doors,Price (INR),Fuel per 100KM,Total fuel used,Seats,Passed road safety
0,Mercedes-Benz GLC,Black,6556,4,2923000,8.8,576.928,5,True
1,Volkswagen Virtus,Black,177392,4,605000,8.8,15610.496,5,True
2,Ford Mustang,White,7811,3,717000,8.8,687.368,5,True
3,Honda Civic,Green,52124,4,1368000,8.8,4586.912,5,True
4,Tesla Model 3,Brown,154472,4,1573000,8.8,13593.536,5,True
5,BMW 3 Series,Pearl White,89194,4,3469000,8.8,7849.072,5,True
6,Maruti Suzuki Swift,Black,24312,4,1065000,8.8,2139.456,5,True
7,BMW 5 Series,Blue,211583,2,2900000,8.8,18619.304,5,True
8,MG Hector,Black,144714,4,2258000,8.8,12734.832,5,True
9,Kia Seltos,Yellow,50407,4,416000,8.8,4435.816,5,True

Let’s shuffle the rows using sample(frac=1) so the data is in a random order.

In [71]:
car_sales.sample(frac=0.02)

,Make,Colour,Odometer (km),Doors,Price (INR),Fuel per 100KM,Total fuel used,Seats,Passed road safety
23,Maruti Suzuki Swift,Black,76939,4,653000,8.8,6770.632,5,True
215,Lexus ES,Yellow,5598,2,3455000,8.8,492.624,5,True
11,Volvo XC60,Red,42638,4,3316000,8.8,3752.144,5,True
243,Kia Sonet,Grey,98617,4,580000,8.8,8678.296,5,True
459,Tata Punch,White,47016,5,559000,8.8,4137.408,5,True
193,Toyota Corolla,Yellow,179778,4,339000,8.8,15820.464,5,True
44,Skoda Octavia,Silver,106539,4,663000,8.8,9375.432,5,True
489,Kia Seltos,Green,155666,4,259000,8.8,13698.608,5,True
252,Hyundai Tucson,Green,218458,4,391000,8.8,19224.304,5,True
141,Kia Sportage,Grey,31051,4,1020000,8.8,2732.488,5,True

In [79]:
car_sales_shuffled = car_sales.sample(frac=0.1)

In [80]:
car_sales_shuffled

,Make,Colour,Odometer (km),Doors,Price (INR),Fuel per 100KM,Total fuel used,Seats,Passed road safety
251,Honda Accord,Pearl White,46057,3,1232000,8.8,4053.016,5,True
159,Jeep Compass,Green,9619,4,722000,8.8,846.472,5,True
465,BMW 5 Series,Pearl White,202782,4,3128000,8.8,17844.816,5,True
473,Mahindra XUV700,Pearl White,3235,4,2529000,8.8,284.680,5,True
498,Porsche Macan,Red,17609,4,4913000,8.8,1549.592,5,True
393,Mercedes-Benz GLC,Pearl White,216790,4,1751000,8.8,19077.520,5,True
130,Kia Sonet,Red,111543,5,871000,8.8,9815.784,5,True
264,Porsche Macan,Black,122924,4,3452000,8.8,10817.312,5,True
354,Volkswagen Polo,Red,200240,4,238000,8.8,17621.120,5,True
185,Chevrolet Malibu,Grey,139242,4,1229000,8.8,12253.296,5,True
166,Mazda CX-5,Silver,130646,5,611000,8.8,11496.848,5,True
223,Nissan Magnite,Green,79070,4,250000,8.8,6958.160,5,True
269,Mahindra XUV700,Yellow,124683,4,824000,8.8,10972.104,5,True
430,Kia Sportage,Green,189945,4,232000,8.8,16715.160,5,True
165,Toyota Corolla,Green,106952,3,409000,8.8,9411.776,5,True
308,Ford Focus,Red,81284,4,1015000,8.8,7152.992,5,True
84,Mahindra XUV700,Brown,115811,4,1256000,8.8,10191.368,5,True
361,Jeep Compass,Yellow,193808,4,728000,8.8,17055.104,5,True
208,Honda Accord,Black,25478,4,914000,8.8,2242.064,5,True
405,Porsche Macan,Black,178335,4,3661000,8.8,15693.480,5,True
355,Tata Punch,Green,51027,4,552000,8.8,4490.376,5,True
395,Skoda Octavia,White,68363,4,1064000,8.8,6015.944,5,True
469,Mercedes-Benz GLC,Silver,193896,4,2022000,8.8,17062.848,5,True
378,Hyundai i20,Black,90797,5,994000,8.8,7990.136,5,True
422,Skoda Octavia,Blue,37554,5,926000,8.8,3304.752,5,True
214,Jeep Compass,Blue,49757,5,747000,8.8,4378.616,5,True
480,Ford Mustang,Yellow,35684,4,1554000,8.8,3140.192,5,True
243,Kia Sonet,Grey,98617,4,580000,8.8,8678.296,5,True
296,Kia Carens,Yellow,138352,4,500000,8.8,12174.976,5,True
238,Honda City,Yellow,59286,4,1417000,8.8,5217.168,5,True
221,Volkswagen Virtus,Black,124845,4,708000,8.8,10986.360,5,True
344,Volvo XC60,Black,180515,2,2914000,8.8,15885.320,5,True
409,Mahindra Thar,Black,11872,4,1084000,8.8,1044.736,5,True
60,Hyundai Creta,Yellow,55215,4,670000,8.8,4858.920,5,True
265,Mahindra Thar,White,92259,4,680000,8.8,8118.792,5,True
82,Mercedes-Benz C-Class,Yellow,149187,4,4606000,8.8,13128.456,5,True
325,Honda Accord,Grey,32148,4,426000,8.8,2829.024,5,True
495,Toyota RAV4,Black,77445,4,794000,8.8,6815.160,5,True
229,Lexus ES,Pearl White,118372,5,3201000,8.8,10416.736,5,True
54,Tata Nexon,Brown,82883,5,278000,8.8,7293.704,5,True
134,Skoda Kushaq,Green,156445,4,419000,8.8,13767.160,5,True
191,MG Hector,Brown,27958,4,2417000,8.8,2460.304,5,True
119,Renault Duster,Brown,27666,4,955000,8.8,2434.608,5,True
53,Hyundai i20,Red,62570,4,540000,8.8,5506.160,5,True
12,Honda Amaze,Black,159680,4,938000,8.8,14051.840,5,True
490,Skoda Octavia,Red,43604,4,398000,8.8,3837.152,5,True
390,Volvo XC60,Blue,50544,4,2954000,8.8,4447.872,5,True
415,Volvo XC60,Green,111182,4,2276000,8.8,9784.016,5,True
132,Audi A4,Red,31340,4,7173000,8.8,2757.920,5,True
291,Toyota Camry,White,108762,2,1857000,8.8,9571.056,5,True

Want to see how we can sort the data back into order?

In [87]:
car_sales_shuffled = car_sales_shuffled.reset_index(drop=True)

OR

In [81]:
# car_sales_shuffled.reset_index(drop=True, inplace=True)

It adds the "old" shuffled index as a new column, on the top of it, it doesn’t update the original DataFrame unless we assign the result back to it.

In [86]:
car_sales_shuffled

,Make,Colour,Odometer (km),Doors,Price (INR),Fuel per 100KM,Total fuel used,Seats,Passed road safety
0,Honda Accord,Pearl White,46057,3,1232000,8.8,4053.016,5,True
1,Jeep Compass,Green,9619,4,722000,8.8,846.472,5,True
2,BMW 5 Series,Pearl White,202782,4,3128000,8.8,17844.816,5,True
3,Mahindra XUV700,Pearl White,3235,4,2529000,8.8,284.680,5,True
4,Porsche Macan,Red,17609,4,4913000,8.8,1549.592,5,True
5,Mercedes-Benz GLC,Pearl White,216790,4,1751000,8.8,19077.520,5,True
6,Kia Sonet,Red,111543,5,871000,8.8,9815.784,5,True
7,Porsche Macan,Black,122924,4,3452000,8.8,10817.312,5,True
8,Volkswagen Polo,Red,200240,4,238000,8.8,17621.120,5,True
9,Chevrolet Malibu,Grey,139242,4,1229000,8.8,12253.296,5,True
10,Mazda CX-5,Silver,130646,5,611000,8.8,11496.848,5,True
11,Nissan Magnite,Green,79070,4,250000,8.8,6958.160,5,True
12,Mahindra XUV700,Yellow,124683,4,824000,8.8,10972.104,5,True
13,Kia Sportage,Green,189945,4,232000,8.8,16715.160,5,True
14,Toyota Corolla,Green,106952,3,409000,8.8,9411.776,5,True
15,Ford Focus,Red,81284,4,1015000,8.8,7152.992,5,True
16,Mahindra XUV700,Brown,115811,4,1256000,8.8,10191.368,5,True
17,Jeep Compass,Yellow,193808,4,728000,8.8,17055.104,5,True
18,Honda Accord,Black,25478,4,914000,8.8,2242.064,5,True
19,Porsche Macan,Black,178335,4,3661000,8.8,15693.480,5,True
20,Tata Punch,Green,51027,4,552000,8.8,4490.376,5,True
21,Skoda Octavia,White,68363,4,1064000,8.8,6015.944,5,True
22,Mercedes-Benz GLC,Silver,193896,4,2022000,8.8,17062.848,5,True
23,Hyundai i20,Black,90797,5,994000,8.8,7990.136,5,True
24,Skoda Octavia,Blue,37554,5,926000,8.8,3304.752,5,True
25,Jeep Compass,Blue,49757,5,747000,8.8,4378.616,5,True
26,Ford Mustang,Yellow,35684,4,1554000,8.8,3140.192,5,True
27,Kia Sonet,Grey,98617,4,580000,8.8,8678.296,5,True
28,Kia Carens,Yellow,138352,4,500000,8.8,12174.976,5,True
29,Honda City,Yellow,59286,4,1417000,8.8,5217.168,5,True
30,Volkswagen Virtus,Black,124845,4,708000,8.8,10986.360,5,True
31,Volvo XC60,Black,180515,2,2914000,8.8,15885.320,5,True
32,Mahindra Thar,Black,11872,4,1084000,8.8,1044.736,5,True
33,Hyundai Creta,Yellow,55215,4,670000,8.8,4858.920,5,True
34,Mahindra Thar,White,92259,4,680000,8.8,8118.792,5,True
35,Mercedes-Benz C-Class,Yellow,149187,4,4606000,8.8,13128.456,5,True
36,Honda Accord,Grey,32148,4,426000,8.8,2829.024,5,True
37,Toyota RAV4,Black,77445,4,794000,8.8,6815.160,5,True
38,Lexus ES,Pearl White,118372,5,3201000,8.8,10416.736,5,True
39,Tata Nexon,Brown,82883,5,278000,8.8,7293.704,5,True
40,Skoda Kushaq,Green,156445,4,419000,8.8,13767.160,5,True
41,MG Hector,Brown,27958,4,2417000,8.8,2460.304,5,True
42,Renault Duster,Brown,27666,4,955000,8.8,2434.608,5,True
43,Hyundai i20,Red,62570,4,540000,8.8,5506.160,5,True
44,Honda Amaze,Black,159680,4,938000,8.8,14051.840,5,True
45,Skoda Octavia,Red,43604,4,398000,8.8,3837.152,5,True
46,Volvo XC60,Blue,50544,4,2954000,8.8,4447.872,5,True
47,Volvo XC60,Green,111182,4,2276000,8.8,9784.016,5,True
48,Audi A4,Red,31340,4,7173000,8.8,2757.920,5,True
49,Toyota Camry,White,108762,2,1857000,8.8,9571.056,5,True

In [74]:
# car_sales_shuffled = car_sales_shuffled.reset_index(drop=True, inplace=True)

In [83]:
car_sales_shuffled

,Make,Colour,Odometer (km),Doors,Price (INR),Fuel per 100KM,Total fuel used,Seats,Passed road safety
0,Honda Accord,Pearl White,46057,3,1232000,8.8,4053.016,5,True
1,Jeep Compass,Green,9619,4,722000,8.8,846.472,5,True
2,BMW 5 Series,Pearl White,202782,4,3128000,8.8,17844.816,5,True
3,Mahindra XUV700,Pearl White,3235,4,2529000,8.8,284.680,5,True
4,Porsche Macan,Red,17609,4,4913000,8.8,1549.592,5,True
5,Mercedes-Benz GLC,Pearl White,216790,4,1751000,8.8,19077.520,5,True
6,Kia Sonet,Red,111543,5,871000,8.8,9815.784,5,True
7,Porsche Macan,Black,122924,4,3452000,8.8,10817.312,5,True
8,Volkswagen Polo,Red,200240,4,238000,8.8,17621.120,5,True
9,Chevrolet Malibu,Grey,139242,4,1229000,8.8,12253.296,5,True
10,Mazda CX-5,Silver,130646,5,611000,8.8,11496.848,5,True
11,Nissan Magnite,Green,79070,4,250000,8.8,6958.160,5,True
12,Mahindra XUV700,Yellow,124683,4,824000,8.8,10972.104,5,True
13,Kia Sportage,Green,189945,4,232000,8.8,16715.160,5,True
14,Toyota Corolla,Green,106952,3,409000,8.8,9411.776,5,True
15,Ford Focus,Red,81284,4,1015000,8.8,7152.992,5,True
16,Mahindra XUV700,Brown,115811,4,1256000,8.8,10191.368,5,True
17,Jeep Compass,Yellow,193808,4,728000,8.8,17055.104,5,True
18,Honda Accord,Black,25478,4,914000,8.8,2242.064,5,True
19,Porsche Macan,Black,178335,4,3661000,8.8,15693.480,5,True
20,Tata Punch,Green,51027,4,552000,8.8,4490.376,5,True
21,Skoda Octavia,White,68363,4,1064000,8.8,6015.944,5,True
22,Mercedes-Benz GLC,Silver,193896,4,2022000,8.8,17062.848,5,True
23,Hyundai i20,Black,90797,5,994000,8.8,7990.136,5,True
24,Skoda Octavia,Blue,37554,5,926000,8.8,3304.752,5,True
25,Jeep Compass,Blue,49757,5,747000,8.8,4378.616,5,True
26,Ford Mustang,Yellow,35684,4,1554000,8.8,3140.192,5,True
27,Kia Sonet,Grey,98617,4,580000,8.8,8678.296,5,True
28,Kia Carens,Yellow,138352,4,500000,8.8,12174.976,5,True
29,Honda City,Yellow,59286,4,1417000,8.8,5217.168,5,True
30,Volkswagen Virtus,Black,124845,4,708000,8.8,10986.360,5,True
31,Volvo XC60,Black,180515,2,2914000,8.8,15885.320,5,True
32,Mahindra Thar,Black,11872,4,1084000,8.8,1044.736,5,True
33,Hyundai Creta,Yellow,55215,4,670000,8.8,4858.920,5,True
34,Mahindra Thar,White,92259,4,680000,8.8,8118.792,5,True
35,Mercedes-Benz C-Class,Yellow,149187,4,4606000,8.8,13128.456,5,True
36,Honda Accord,Grey,32148,4,426000,8.8,2829.024,5,True
37,Toyota RAV4,Black,77445,4,794000,8.8,6815.160,5,True
38,Lexus ES,Pearl White,118372,5,3201000,8.8,10416.736,5,True
39,Tata Nexon,Brown,82883,5,278000,8.8,7293.704,5,True
40,Skoda Kushaq,Green,156445,4,419000,8.8,13767.160,5,True
41,MG Hector,Brown,27958,4,2417000,8.8,2460.304,5,True
42,Renault Duster,Brown,27666,4,955000,8.8,2434.608,5,True
43,Hyundai i20,Red,62570,4,540000,8.8,5506.160,5,True
44,Honda Amaze,Black,159680,4,938000,8.8,14051.840,5,True
45,Skoda Octavia,Red,43604,4,398000,8.8,3837.152,5,True
46,Volvo XC60,Blue,50544,4,2954000,8.8,4447.872,5,True
47,Volvo XC60,Green,111182,4,2276000,8.8,9784.016,5,True
48,Audi A4,Red,31340,4,7173000,8.8,2757.920,5,True
49,Toyota Camry,White,108762,2,1857000,8.8,9571.056,5,True

In [76]:
# car_sales_shuffled = car_sales_shuffled.drop(columns=["index"])

In [84]:
car_sales_shuffled

,Make,Colour,Odometer (km),Doors,Price (INR),Fuel per 100KM,Total fuel used,Seats,Passed road safety
0,Honda Accord,Pearl White,46057,3,1232000,8.8,4053.016,5,True
1,Jeep Compass,Green,9619,4,722000,8.8,846.472,5,True
2,BMW 5 Series,Pearl White,202782,4,3128000,8.8,17844.816,5,True
3,Mahindra XUV700,Pearl White,3235,4,2529000,8.8,284.680,5,True
4,Porsche Macan,Red,17609,4,4913000,8.8,1549.592,5,True
5,Mercedes-Benz GLC,Pearl White,216790,4,1751000,8.8,19077.520,5,True
6,Kia Sonet,Red,111543,5,871000,8.8,9815.784,5,True
7,Porsche Macan,Black,122924,4,3452000,8.8,10817.312,5,True
8,Volkswagen Polo,Red,200240,4,238000,8.8,17621.120,5,True
9,Chevrolet Malibu,Grey,139242,4,1229000,8.8,12253.296,5,True
10,Mazda CX-5,Silver,130646,5,611000,8.8,11496.848,5,True
11,Nissan Magnite,Green,79070,4,250000,8.8,6958.160,5,True
12,Mahindra XUV700,Yellow,124683,4,824000,8.8,10972.104,5,True
13,Kia Sportage,Green,189945,4,232000,8.8,16715.160,5,True
14,Toyota Corolla,Green,106952,3,409000,8.8,9411.776,5,True
15,Ford Focus,Red,81284,4,1015000,8.8,7152.992,5,True
16,Mahindra XUV700,Brown,115811,4,1256000,8.8,10191.368,5,True
17,Jeep Compass,Yellow,193808,4,728000,8.8,17055.104,5,True
18,Honda Accord,Black,25478,4,914000,8.8,2242.064,5,True
19,Porsche Macan,Black,178335,4,3661000,8.8,15693.480,5,True
20,Tata Punch,Green,51027,4,552000,8.8,4490.376,5,True
21,Skoda Octavia,White,68363,4,1064000,8.8,6015.944,5,True
22,Mercedes-Benz GLC,Silver,193896,4,2022000,8.8,17062.848,5,True
23,Hyundai i20,Black,90797,5,994000,8.8,7990.136,5,True
24,Skoda Octavia,Blue,37554,5,926000,8.8,3304.752,5,True
25,Jeep Compass,Blue,49757,5,747000,8.8,4378.616,5,True
26,Ford Mustang,Yellow,35684,4,1554000,8.8,3140.192,5,True
27,Kia Sonet,Grey,98617,4,580000,8.8,8678.296,5,True
28,Kia Carens,Yellow,138352,4,500000,8.8,12174.976,5,True
29,Honda City,Yellow,59286,4,1417000,8.8,5217.168,5,True
30,Volkswagen Virtus,Black,124845,4,708000,8.8,10986.360,5,True
31,Volvo XC60,Black,180515,2,2914000,8.8,15885.320,5,True
32,Mahindra Thar,Black,11872,4,1084000,8.8,1044.736,5,True
33,Hyundai Creta,Yellow,55215,4,670000,8.8,4858.920,5,True
34,Mahindra Thar,White,92259,4,680000,8.8,8118.792,5,True
35,Mercedes-Benz C-Class,Yellow,149187,4,4606000,8.8,13128.456,5,True
36,Honda Accord,Grey,32148,4,426000,8.8,2829.024,5,True
37,Toyota RAV4,Black,77445,4,794000,8.8,6815.160,5,True
38,Lexus ES,Pearl White,118372,5,3201000,8.8,10416.736,5,True
39,Tata Nexon,Brown,82883,5,278000,8.8,7293.704,5,True
40,Skoda Kushaq,Green,156445,4,419000,8.8,13767.160,5,True
41,MG Hector,Brown,27958,4,2417000,8.8,2460.304,5,True
42,Renault Duster,Brown,27666,4,955000,8.8,2434.608,5,True
43,Hyundai i20,Red,62570,4,540000,8.8,5506.160,5,True
44,Honda Amaze,Black,159680,4,938000,8.8,14051.840,5,True
45,Skoda Octavia,Red,43604,4,398000,8.8,3837.152,5,True
46,Volvo XC60,Blue,50544,4,2954000,8.8,4447.872,5,True
47,Volvo XC60,Green,111182,4,2276000,8.8,9784.016,5,True
48,Audi A4,Red,31340,4,7173000,8.8,2757.920,5,True
49,Toyota Camry,White,108762,2,1857000,8.8,9571.056,5,True

Let's see how we can apply a function to a or an entire column.

In [95]:
car_sales.head(10)

,Make,Colour,Odometer (km),Doors,Price (INR),Fuel per 100KM,Total fuel used,Seats,Passed road safety
0,Mercedes-Benz GLC,Black,1600.585938,4,2923000,8.8,576.928,5,True
1,Volkswagen Virtus,Black,43308.593750,4,605000,8.8,15610.496,5,True
2,Ford Mustang,White,1906.982422,3,717000,8.8,687.368,5,True
3,Honda Civic,Green,12725.585938,4,1368000,8.8,4586.912,5,True
4,Tesla Model 3,Brown,37712.890625,4,1573000,8.8,13593.536,5,True
5,BMW 3 Series,Pearl White,21775.878906,4,3469000,8.8,7849.072,5,True
6,Maruti Suzuki Swift,Black,5935.546875,4,1065000,8.8,2139.456,5,True
7,BMW 5 Series,Blue,51656.005859,2,2900000,8.8,18619.304,5,True
8,MG Hector,Black,35330.566406,4,2258000,8.8,12734.832,5,True
9,Kia Seltos,Yellow,12306.396484,4,416000,8.8,4435.816,5,True

In [94]:
car_sales["Odometer (km)"] = car_sales["Odometer (km)"].apply(lambda x: x/1.6) #KM TO MILES

In [96]:
car_sales

,Make,Colour,Odometer (km),Doors,Price (INR),Fuel per 100KM,Total fuel used,Seats,Passed road safety
0,Mercedes-Benz GLC,Black,1600.585938,4,2923000,8.8,576.928,5,True
1,Volkswagen Virtus,Black,43308.593750,4,605000,8.8,15610.496,5,True
2,Ford Mustang,White,1906.982422,3,717000,8.8,687.368,5,True
3,Honda Civic,Green,12725.585938,4,1368000,8.8,4586.912,5,True
4,Tesla Model 3,Brown,37712.890625,4,1573000,8.8,13593.536,5,True
...,...,...,...,...,...,...,...,...,...
495,Toyota RAV4,Black,18907.470703,4,794000,8.8,6815.160,5,True
496,Kia Carens,Silver,22292.968750,4,1036000,8.8,8035.456,5,True
497,Kia Sonet,Brown,22291.015625,4,978000,8.8,8034.752,5,True
498,Porsche Macan,Red,4299.072266,4,4913000,8.8,1549.592,5,True
499,Maruti Suzuki Swift,Black,43336.914062,4,485000,8.8,15620.704,5,True