___________________________

## DAY 16

In [1]:
import pandas as pd

# 2 Main Datatypes

In [5]:
series = pd.Series(["BMW", "Mercedes", "Audi"])

In [6]:
series

0         BMW
1    Mercedes
2        Audi
dtype: str

# Series = 1 Dimensional

In [9]:
colours = pd.Series(["Black", "Magenta", "White"])
colours

0      Black
1    Magenta
2      White
dtype: str

# DataFrame = 2 Dimensional

In [37]:
car_data = pd.DataFrame({"Cars": series, "Colours": colours})
print(car_data)
car_data.iloc[2,1]

       Cars  Colours
0       BMW    Black
1  Mercedes  Magenta
2      Audi    White

'White'

# IMPORTING DATA

In [29]:
car_sales = pd.read_csv("cars_dataset.csv")
car_sales

                    Make  Colour  Odometer (km)  Doors  Price (INR)
0      Mercedes-Benz GLC   Black           6556      4      2923000
1      Volkswagen Virtus   Black         177392      4       605000
2           Ford Mustang   White           7811      3       717000
3            Honda Civic   Green          52124      4      1368000
4          Tesla Model 3   Brown         154472      4      1573000
..                   ...     ...            ...    ...          ...
495          Toyota RAV4   Black          77445      4       794000
496           Kia Carens  Silver          91312      4      1036000
497            Kia Sonet   Brown          91304      4       978000
498        Porsche Macan     Red          17609      4      4913000
499  Maruti Suzuki Swift   Black         177508      4       485000

[500 rows x 5 columns]

# Importing Data

In [50]:
car_sales.to_csv("exported-car-sales.csv", index=False)

Well, WE used index = False so pandas wouldn't write the DataFrame's index NO. as an additional column in  exported CSV file. as we only want our actual data columns, not the extra index column.

In [51]:
exported_car_sales = pd.read_csv("exported-car-sales.csv")
exported_car_sales

                    Make  Colour  Odometer (km)  Doors  Price (INR)
0      Mercedes-Benz GLC   Black           6556      4      2923000
1      Volkswagen Virtus   Black         177392      4       605000
2           Ford Mustang   White           7811      3       717000
3            Honda Civic   Green          52124      4      1368000
4          Tesla Model 3   Brown         154472      4      1573000
..                   ...     ...            ...    ...          ...
495          Toyota RAV4   Black          77445      4       794000
496           Kia Carens  Silver          91312      4      1036000
497            Kia Sonet   Brown          91304      4       978000
498        Porsche Macan     Red          17609      4      4913000
499  Maruti Suzuki Swift   Black         177508      4       485000

[500 rows x 5 columns]

With that, we've learned about the main data structures: DataFrames and Series, + how to import and export data, && cleared up all the doubts we had along the way with the help of our dearest tutor AI, haha.

___________________________

## DAY 17 - BEGINS!!!!!!

___________________________

## Describe data

In [56]:
car_sales.dtypes

Make               str
Colour             str
Odometer (km)    int64
Doors            int64
Price (INR)      int64
dtype: object

In [57]:
car_sales.columns

Index(['Make', 'Colour', 'Odometer (km)', 'Doors', 'Price (INR)'], dtype='str')

In [60]:
car_columns = car_sales.columns
car_columns

Index(['Make', 'Colour', 'Odometer (km)', 'Doors', 'Price (INR)'], dtype='str')

Let's try out to manipulate the columns name, we already saved it under a variable called car_columns.. let's do it.

In [63]:
car_sales = car_sales.rename(columns={
    "Make": "Brand",
    "Colour": "Color",
    "Odometer  (km)": "Mileage",
    "Price (INR)": "Price"
})

It's time to see the changes!!!!!!

In [64]:
car_sales.columns

Index(['Brand', 'Color', 'Odometer (km)', 'Doors', 'Price'], dtype='str')

Haha, we intentionally added an extra space b/w Odometer and (km) here: "Odometer  (km)": "Mileage", and look, the renaming doesn't take place.

In [66]:
car_sales = car_sales.rename(columns={
    "Make": "Brand",
    "Colour": "Color",
    "Odometer (km)": "Mileage",
    "Price (INR)": "Price"
})
car_sales.columns # Alrighty!!! it's fixed...

Index(['Brand', 'Color', 'Mileage', 'Doors', 'Price'], dtype='str')

Let's look at something else. ah what about the index here?? let's see it

In [67]:
car_sales.index

RangeIndex(start=0, stop=500, step=1)

In [68]:
car_sales

                   Brand   Color  Mileage  Doors    Price
0      Mercedes-Benz GLC   Black     6556      4  2923000
1      Volkswagen Virtus   Black   177392      4   605000
2           Ford Mustang   White     7811      3   717000
3            Honda Civic   Green    52124      4  1368000
4          Tesla Model 3   Brown   154472      4  1573000
..                   ...     ...      ...    ...      ...
495          Toyota RAV4   Black    77445      4   794000
496           Kia Carens  Silver    91312      4  1036000
497            Kia Sonet   Brown    91304      4   978000
498        Porsche Macan     Red    17609      4  4913000
499  Maruti Suzuki Swift   Black   177508      4   485000

[500 rows x 5 columns]

# Let's looook at some functions!!!!!
that we can call and see what magic they can do, and add to our mental model.

In [69]:
car_sales.describe()

             Mileage       Doors         Price
count     500.000000  500.000000  5.000000e+02
mean   112281.954000    3.880000  1.513670e+06
std     65726.248884    0.694669  1.403873e+06
min      1600.000000    2.000000  1.650000e+05
25%     54771.750000    4.000000  6.027500e+05
50%    113569.000000    4.000000  9.540000e+05
75%    172042.500000    4.000000  1.944000e+06
max    219853.000000    5.000000  7.210000e+06

Describe's works only on numeric columns. gives us statisticsl summary: their count, means, standard deviation (i think thats what means by "std"), minimum and maxiumum.

remember seeing 3.88 under ""Doors"" doesn't mean we're out here buying cars with 3.88 doors (LOL) it's simply the avg. number of doors across all 500 cars in our dataset.

In [70]:
car_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Brand    500 non-null    str
 1   Color    500 non-null    str
 2   Mileage  500 non-null    int64
 3   Doors    500 non-null    int64
 4   Price    500 non-null    int64
dtypes: int64(3), str(2)
memory usage: 19.7 KB

# Interestingly, info() gives us a quick overview of our DataFrame all at once

it shows info's about what index, columns, and dtypes attribute did it along with the memory usage, so we don't have to check everything separately. pretty handy haha

In [72]:
car_sales.mean(numeric_only=True)

Mileage     112281.954
Doors            3.880
Price      1513670.000
dtype: float64

We can even call mean on individual series!!!!! let's try this out

In [74]:
car_price = pd.Series([2000, 4000, 8000, 16000 ])
car_price.mean()

np.float64(7500.0)

In [75]:
car_sales.sum()

Brand      Mercedes-Benz GLCVolkswagen VirtusFord Mustang...
Color      BlackBlackWhiteGreenBrownPearl WhiteBlackBlueB...
Mileage                                             56140977
Doors                                                   1940
Price                                              756835000
dtype: object

This is gonna sum up all the different columns value

we can also select a specific column and call sum() to calculate the total of its values.

In [76]:
car_sales["Price"].sum()

np.int64(756835000)

In [77]:
len(car_sales)

500