## VIEWING AND SELECTING DATA

In [2]:
import pandas as pd

In [9]:
car_sales = pd.read_csv("exported-car-sales.csv")

In [10]:
car_sales

                    Make  Colour  Odometer (km)  Doors  Price (INR)
0      Mercedes-Benz GLC   Black           6556      4      2923000
1      Volkswagen Virtus   Black         177392      4       605000
2           Ford Mustang   White           7811      3       717000
3            Honda Civic   Green          52124      4      1368000
4          Tesla Model 3   Brown         154472      4      1573000
..                   ...     ...            ...    ...          ...
495          Toyota RAV4   Black          77445      4       794000
496           Kia Carens  Silver          91312      4      1036000
497            Kia Sonet   Brown          91304      4       978000
498        Porsche Macan     Red          17609      4      4913000
499  Maruti Suzuki Swift   Black         177508      4       485000

[500 rows x 5 columns]

In [11]:
car_sales.head()

                Make Colour  Odometer (km)  Doors  Price (INR)
0  Mercedes-Benz GLC  Black           6556      4      2923000
1  Volkswagen Virtus  Black         177392      4       605000
2       Ford Mustang  White           7811      3       717000
3        Honda Civic  Green          52124      4      1368000
4      Tesla Model 3  Brown         154472      4      1573000

It returns the first 5 rows of our DataFrame by default. basically, it gives us a quick snapshot of our data in a small space, helping us get an overview of what our data looks like/what it contains.

But, but, but... we can check more than just the first 5 rows. Let's see how. 👀

In [13]:
car_sales.head(7)

                  Make       Colour  Odometer (km)  Doors  Price (INR)
0    Mercedes-Benz GLC        Black           6556      4      2923000
1    Volkswagen Virtus        Black         177392      4       605000
2         Ford Mustang        White           7811      3       717000
3          Honda Civic        Green          52124      4      1368000
4        Tesla Model 3        Brown         154472      4      1573000
5         BMW 3 Series  Pearl White          89194      4      3469000
6  Maruti Suzuki Swift        Black          24312      4      1065000

If we ever want to check the bottom rows of our DataFrame, we can do that too.

In [16]:
car_sales.tail()

                    Make  Colour  Odometer (km)  Doors  Price (INR)
495          Toyota RAV4   Black          77445      4       794000
496           Kia Carens  Silver          91312      4      1036000
497            Kia Sonet   Brown          91304      4       978000
498        Porsche Macan     Red          17609      4      4913000
499  Maruti Suzuki Swift   Black         177508      4       485000

 OR

In [18]:
car_sales.tail(10)

                    Make       Colour  Odometer (km)  Doors  Price (INR)
490        Skoda Octavia          Red          43604      4       398000
491             Lexus RX  Pearl White         197311      4      2211000
492        Nissan Altima         Blue          58196      4      1088000
493          Honda Amaze       Yellow          57942      4       851000
494      Toyota Fortuner       Yellow         180993      4      1687000
495          Toyota RAV4        Black          77445      4       794000
496           Kia Carens       Silver          91312      4      1036000
497            Kia Sonet        Brown          91304      4       978000
498        Porsche Macan          Red          17609      4      4913000
499  Maruti Suzuki Swift        Black         177508      4       485000

## .loc and .iloc
First, let's do some fun experiments

In [20]:
animals = pd.Series(["lion", "tiger", "wolf", "pandas", "rabbit"], index=[0, 3, 9, 8, 3])

In [21]:
animals

0      lion
3     tiger
9      wolf
8    pandas
3    rabbit
dtype: str

In [24]:
animals.loc[8]

'pandas'

In [25]:
animals.loc[3]

3     tiger
3    rabbit
dtype: str

In [31]:
car_sales.head(10)

                  Make       Colour  Odometer (km)  Doors  Price (INR)
0    Mercedes-Benz GLC        Black           6556      4      2923000
1    Volkswagen Virtus        Black         177392      4       605000
2         Ford Mustang        White           7811      3       717000
3          Honda Civic        Green          52124      4      1368000
4        Tesla Model 3        Brown         154472      4      1573000
5         BMW 3 Series  Pearl White          89194      4      3469000
6  Maruti Suzuki Swift        Black          24312      4      1065000
7         BMW 5 Series         Blue         211583      2      2900000
8            MG Hector        Black         144714      4      2258000
9           Kia Seltos       Yellow          50407      4       416000

Now, let's give our car_sales DataFrame a try with .loc.

In [27]:
car_sales.loc[3]

Make             Honda Civic
Colour                 Green
Odometer (km)          52124
Doors                      4
Price (INR)          1368000
Name: 3, dtype: object

## Now it's .iloc's time to shine

In [36]:
animals

0      lion
3     tiger
9      wolf
8    pandas
3    rabbit
dtype: str

In [35]:
animals.iloc[3]

'pandas'

.iloc refers to position. remember, Python lists, Pandas DataFrames, & Series use 0-based positions, meaning the first element is at position 0.

.iloc refers to position whereas .loc refers to index label

In [40]:
car_sales.iloc[5]

Make             BMW 3 Series
Colour            Pearl White
Odometer (km)           89194
Doors                       4
Price (INR)           3469000
Name: 5, dtype: object

In [41]:
car_sales.loc[5]

Make             BMW 3 Series
Colour            Pearl White
Odometer (km)           89194
Doors                       4
Price (INR)           3469000
Name: 5, dtype: object

Since both have the same index label and position, the outputs are the same.

# List Slicing with .iloc and .loc

In [45]:
car_sales.head(10)

                  Make       Colour  Odometer (km)  Doors  Price (INR)
0    Mercedes-Benz GLC        Black           6556      4      2923000
1    Volkswagen Virtus        Black         177392      4       605000
2         Ford Mustang        White           7811      3       717000
3          Honda Civic        Green          52124      4      1368000
4        Tesla Model 3        Brown         154472      4      1573000
5         BMW 3 Series  Pearl White          89194      4      3469000
6  Maruti Suzuki Swift        Black          24312      4      1065000
7         BMW 5 Series         Blue         211583      2      2900000
8            MG Hector        Black         144714      4      2258000
9           Kia Seltos       Yellow          50407      4       416000

In [49]:
car_sales.iloc[:4]

                Make Colour  Odometer (km)  Doors  Price (INR)
0  Mercedes-Benz GLC  Black           6556      4      2923000
1  Volkswagen Virtus  Black         177392      4       605000
2       Ford Mustang  White           7811      3       717000
3        Honda Civic  Green          52124      4      1368000

In [47]:
car_sales.loc[:4]

                Make Colour  Odometer (km)  Doors  Price (INR)
0  Mercedes-Benz GLC  Black           6556      4      2923000
1  Volkswagen Virtus  Black         177392      4       605000
2       Ford Mustang  White           7811      3       717000
3        Honda Civic  Green          52124      4      1368000
4      Tesla Model 3  Brown         154472      4      1573000

Now, here's something interesting.

With .iloc, the ending position is excluded, just like normal Python list slicing. so, car_sales.iloc[:4] returns the first 4 rows.

But with .loc, the ending index label is included. so, car_sales.loc[:4] returns 5 rows because it includes the row with index label 4.

# Two Ways of Selecting a Column.

In [50]:
car_sales["Make"] # The first way!

0        Mercedes-Benz GLC
1        Volkswagen Virtus
2             Ford Mustang
3              Honda Civic
4            Tesla Model 3
              ...
495            Toyota RAV4
496             Kia Carens
497              Kia Sonet
498          Porsche Macan
499    Maruti Suzuki Swift
Name: Make, Length: 500, dtype: str

In [51]:
car_sales["Colour"]

0       Black
1       Black
2       White
3       Green
4       Brown
        ...
495     Black
496    Silver
497     Brown
498       Red
499     Black
Name: Colour, Length: 500, dtype: str

In [52]:
car_sales.Make # The second way!

0        Mercedes-Benz GLC
1        Volkswagen Virtus
2             Ford Mustang
3              Honda Civic
4            Tesla Model 3
              ...
495            Toyota RAV4
496             Kia Carens
497              Kia Sonet
498          Porsche Macan
499    Maruti Suzuki Swift
Name: Make, Length: 500, dtype: str

But. but. but. what if our column name contains spaces, like "Odometer (km)"? 

In that case, car_sales.Odometer (km) won't work coz dot notation doesn't support column names w/ spaces or special characters like parentheses.

Instead, we can use bracket notation: car_sales["Odometer (km)"] to access the column.

# LET'S TRY SELECTING A SINGLE COLUMN, BUT WITH A LITTLE FILTERING ON TOP! LET'S DO THIS!!!!!!!!!

In [54]:
car_sales[car_sales["Make"] == "Tesla Model 3"]

              Make  Colour  Odometer (km)  Doors  Price (INR)
4    Tesla Model 3   Brown         154472      4      1573000
14   Tesla Model 3     Red         201408      4      2428000
72   Tesla Model 3    Grey           6203      4      4025000
91   Tesla Model 3  Silver         210792      5      3005000
103  Tesla Model 3   Brown          57520      4      3275000
154  Tesla Model 3  Yellow         153910      5      5260000
195  Tesla Model 3  Yellow         210221      4      2887000
237  Tesla Model 3   Black          91780      4      2742000
427  Tesla Model 3    Blue         185487      4      3861000
439  Tesla Model 3  Silver           4251      4      5946000
446  Tesla Model 3   Black         185380      4      2120000

In [57]:
car_sales[car_sale["Colour"] == "Black"]

                      Make Colour  Odometer (km)  Doors  Price (INR)
0        Mercedes-Benz GLC  Black           6556      4      2923000
1        Volkswagen Virtus  Black         177392      4       605000
6      Maruti Suzuki Swift  Black          24312      4      1065000
8                MG Hector  Black         144714      4      2258000
12             Honda Amaze  Black         159680      4       938000
22          Toyota Corolla  Black         178706      5       581000
23     Maruti Suzuki Swift  Black          76939      4       653000
33           Porsche Macan  Black          64986      4      2597000
38                 Audi A4  Black          25409      4      3846000
50   Mercedes-Benz C-Class  Black         155984      2      2251000
64          Toyota Corolla  Black          19724      5      1745000
99                Lexus ES  Black         108755      4      4191000
106            Honda Civic  Black         168492      4       594000
117           BMW 5 Series  Black         208726      5      1170000
139            Toyota RAV4  Black         215512      2      1082000
144      Volkswagen Virtus  Black         199946      4       358000
157           Honda Accord  Black         123210      4       601000
169         Subaru Outback  Black          72416      4      1767000
183           Skoda Kushaq  Black         116307      4       791000
201             Volvo XC60  Black          36898      4      3812000
208           Honda Accord  Black          25478      4       914000
221      Volkswagen Virtus  Black         124845      4       708000
225          Porsche Macan  Black          21178      4      2078000
228            Honda Amaze  Black         171629      4       922000
232        Hyundai Elantra  Black         218044      3       453000
236           Toyota Camry  Black         151497      4      1089000
237          Tesla Model 3  Black          91780      4      2742000
242           Jeep Compass  Black          37191      4       281000
259      Mercedes-Benz GLC  Black         139094      4      2775000
264          Porsche Macan  Black         122924      4      3452000
270    Maruti Suzuki Swift  Black         132264      4       258000
275    Maruti Suzuki Swift  Black         152761      4       566000
280       Chevrolet Malibu  Black          77540      4       435000
292              MG Hector  Black          98281      4      1974000
301             Kia Seltos  Black         137903      4       876000
304      Mercedes-Benz GLC  Black         202244      4      3686000
314        Mahindra XUV700  Black          20989      4      1608000
317        Volkswagen Golf  Black         175946      4       613000
327            Hyundai i20  Black         144178      4       716000
331           Kia Sportage  Black          81078      4      1429000
333        Mahindra XUV700  Black         117958      4      1815000
335        Volkswagen Golf  Black         135817      4       360000
344             Volvo XC60  Black         180515      2      2914000
348       Chevrolet Malibu  Black          13265      4      1147000
378            Hyundai i20  Black          90797      5       994000
394         Nissan Magnite  Black          48439      5       911000
403             Kia Seltos  Black         147893      3      1076000
405          Porsche Macan  Black         178335      4      3661000
409          Mahindra Thar  Black          11872      4      1084000
410        Volkswagen Golf  Black         123750      2       620000
418        Hyundai Elantra  Black         155698      2       999000
437             Volvo XC60  Black         210453      5      3328000
446          Tesla Model 3  Black         185380      4      2120000
463            Honda Amaze  Black         131279      4       497000
468          Skoda Octavia  Black          21505      4      1038000
495            Toyota RAV4  Black          77445      4       794000
499    Maruti Suzuki Swift  Black         177508      4       485000

In [58]:
car_sale["Colour"] == "Black"

0       True
1       True
2      False
3      False
4      False
       ...
495     True
496    False
497    False
498    False
499     True
Name: Colour, Length: 500, dtype: bool